### ISSUE TITLE
VIA mouse keymap

### ISSUE THREAD

**Issue by scarydisk** [ryodeushii/gem80-qmk-firmware#17]
### Issue Description

I am using Air75v2 with ryo-1.1.4 firmware. I also have 11 Oct 2024 Nuphy RF/Dingle firmware 
I want to add the ability for my keyboard to move the mouse cursor. When I map it with VIA, nothing happens when I hold down the FN button  (Layer 3) and corresponding mouse keymap.
Does anyone else have this issue?

![Screenshot 2024-11-24 115144](https://github.com/user-attachments/assets/7603ee67-d956-453b-8835-05211ec229a4)

**Comment by ryodeushii** [comment]
Hi, basically this feature is disabled in my firmware because it drastically affects performance. I encourage you to fork my repo and change `false` to `true` in thsi file https://github.com/ryodeushii/qmk-firmware/blob/a951d453348cf5d86d68c15ecd946022598cda41/keyboards/nuphy/air75v2/ansi/keyboard.json#L12 

so you can compile my firmware with any additional features you need

**Comment by scarydisk** [comment]
ty for the info
