### ISSUE TITLE
[Bug] When connect via BT, some keys that remapped with VIA do not input

### ISSUE THREAD

**Issue by inzeilife** [ryodeushii/gem80-qmk-firmware#6]
### Describe the Bug

First of all, thank you for developing the custom firmware.

I changed the keymap through VIA. And when I connect via wired, the same keys as I set in VIA are input as expected. But when I connect via Bluetooth, minor language-specific keys like KC_HANJ, KC_HAEN do not seem to be input.

The combinations I tried are as follows:

| Key | Result (wired) | Result (BT) |
| --- | --- | ---|
| Caps Lock -> Left Alt | input | input |
| Left Alt -> KC_HANJ | input | does not input |
| Right Alt -> KC_HAEN | input | does not input |

### Keyboard Used

Halo75 V2 with via_halo75v2-1.1.2-ryodeushii.bin 

### Operating System

Windows 11

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by ryodeushii** [comment]
Hi! Please try with original key names. Ones you've used seems to be aliasesleft. VIA tends to ignore these aliases in general when being assigned.
If they won't work than it would mean, that these keys should be assigned in keymap before compilation. 
But first of all try with these lang1 and lang2 keys


key | alias | comment
-- | -- | --
KC_LANG1 | KC_HAEN | Hangul/English
KC_LANG2 | KC_HANJ | Hanja

**Comment by ryodeushii** [comment]
And one more thing, it is possible, that not all keys would work via Bluetooth, just because of protocol specifics. In wired mode keyboard creates at least 3 HID devices (in 1 composite) each of acts for a different purpose (VIA connectivity, keyboard reports, mouse keys reports - disabled in my fw though, multimedia keys handling, etc). In bluetooth mode all depends on both keyboard level implementation + overall bluetooth protocol support.

**Comment by ryodeushii** [comment]
Close like stale, reopen in case it's needed.
