### ISSUE TITLE
Print Screen key is actually Win + Shift + S?

### ISSUE THREAD

**Issue by GH0STDATA** [ryodeushii/gem80-qmk-firmware#8]
### Issue Description

The title is self explanatory, the `Print Screen` key in VIA is actually set to `Win + Shift + S` for some reason, and not the actual `Print Screen` key itself. This is an issue when it comes to using screenshot applications such as ShareX, which utilize the `Print Screen` key for hotkeys.

**Comment by GH0STDATA** [comment]
After doing some more digging, it looks like you have `Print Screen` set to only be usable when holding the `Fn` key on Windows. When `Fn` is not held, `Print Screen` looks like its assigned to `WIN_PRTA` here: https://github.com/ryodeushii/qmk-firmware/blob/nuphy-keyboards/keyboards/nuphy/halo75v2/ansi/keymaps/via/keymap.c

Thankfully the great thing about VIA is that its customizable, so I fixed this myself in the GUI, but this is a bit of a strange behavior by default.

**Comment by ryodeushii** [comment]
This is how official firmware configured by default, basically WIN_PRTA is just alias for WIN+Shift+S so it would call default clipping tool in windows 7 to 10.
This is not a bug, but intentional change.

If you take a look into official source code you can find that there's actual bug with MAC_PRTA used 
https://github.com/nuphy-src/qmk_firmware/blob/nuphy-keyboards/keyboards/nuphy/halo75_v2/ansi/keymaps/via/keymap.c

While it's WIN+Shift+4 - it won't work in windows at all, that's why I have this key customized.
I just like to keep default state as close to official FW as possible.

**Comment by ryodeushii** [comment]
Closed as stale.
